import{S as l,i as d}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const f="44852213-a2483cc0047435af0fdb3dda4",u="https://pixabay.com/api/";async function m(s){const o=await fetch(`${u}?key=${f}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`);if(!o.ok)throw new Error("Failed to fetch images");return(await o.json()).hits}const c=document.querySelector(".gallery");function h(){c.innerHTML=""}function p(s){const o=s.map(t=>`
        <a href="${t.largeImageURL}" class="gallery__item">
            <img src="${t.webformatURL}" alt="${t.tags}" class="gallery__image"/>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t.likes}</p>
                <p class="info-item"><b>Views:</b> ${t.views}</p>
                <p class="info-item"><b>Comments:</b> ${t.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </a>
    `).join("");c.insertAdjacentHTML("beforeend",o),new l(".gallery a",{}).refresh()}function a(s){d.info({message:s,position:"topRight"})}function y(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector("#search-form"),o=document.querySelector("#search-input");s.addEventListener("submit",async n=>{n.preventDefault();const t=o.value.trim();if(!t){a("Please enter a search term!");return}h(),y();try{const e=await m(t);e.length===0?a("Sorry, there are no images matching your search query. Please try again!"):p(e)}catch{a("An error occurred while fetching images. Please try again later.")}finally{g()}})});
//# sourceMappingURL=commonHelpers.js.map
