import{i as l,S as d}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();document.getElementById("search-form").addEventListener("submit",async function(c){c.preventDefault();const o=document.getElementById("search-query").value.trim();if(!o){l.error({title:"Error",message:"Search query cannot be empty!"});return}const n=document.getElementById("gallery");n.innerHTML="";const s=document.getElementById("loader");s.style.display="block";try{const t=await(await fetch(`https://pixabay.com/api/?key=44852213-a2483cc0047435af0fdb3dda4&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`)).json();if(s.style.display="none",t.hits.length===0){l.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}t.hits.forEach(r=>{const i=document.createElement("a");i.href=r.largeImageURL,i.classList.add("gallery-item"),i.innerHTML=`
              <img src="${r.webformatURL}" alt="${r.tags}">
              <div class="info">
                  <p>Likes: ${r.likes}</p>
                  <p>Views: ${r.views}</p>
                  <p>Comments: ${r.comments}</p>
                  <p>Downloads: ${r.downloads}</p>
              </div>
          `,n.appendChild(i)}),new d(".gallery-item",{}).refresh()}catch{s.style.display="none",l.error({title:"Error",message:"An error occurred while fetching the images. Please try again later!"})}});
//# sourceMappingURL=commonHelpers.js.map
